# Generated by Django 4.2.2 on 2023-07-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_customer_options_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('exclusive_permission', 'new permission type')]},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
